version: '3'

services :

 front:

  build:
   context: './frontend'
   dockerfile: dockerfile
   
  ports:
    - 3000:3000

  container_name: frontend-container

  networks:
   - job-posting-networks


  depends_on:
    - backend

 backend:

  build:
   context: './backend'
   dockerfile: dockerfile
   

  container_name: backend-container

  networks:
   - job-posting-networks
 
  ports:
    - 4444:4444

  depends_on:
   - mongo

 mongo:
   image: mongo
   ports:
     - 27017:27017
   container_name: mongo-container
   networks: 
    - job-posting-networks
   
networks:
 job-posting-networks:

